### ISSUE TITLE
pro启动崩溃反馈

### ISSUE THREAD

**Issue by zmwwxa** [catserver-3-0/CatServerRepo#10]
服务端版本(/version指令获取):
git-CatServer-1.12.2-f278da8
Java版本(打开cmd 输入java -version):
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
操作系统(Linux/Windows, 请指定详细发行版本):
window server 2012 R2(6.3,版本9600）
插件列表(/plugins指令):
[0血bug修复]AntiDeathBug.jar
[ESS]EssentialsX.jar
[ESS]EssentialsXChat.jar
[ESS]EssentialsXProtect.jar
[ESS]EssentialsXSpawn.jar
[VIP管理]VipSystem-3.8.jar
[WE区域显示]WorldEditCUI-1.5.jar
[世界保护]NotBuild.jar
[世界边界]WorldBorder.jar
[传送门]AncientGates.jar
[创世神]worldedit-bukkit-6.1.9.jar
[创世神异步]FastAsyncWorldEdit-bukkit-19.06.12-f71043b-1275-22.2.1.jar
[前置]PlaceholderAPI-2.9.2.jar
[前置]PowerNBT.jar
[前置]ProtocolLib.jar
[前置]Vault.jar
[备份插件]EasyBackup.jar
[多世界]Multiverse-Core-2.6.0.jar
[定时任务]CalendarEvents.jar
[展示框保护]FrameProtect_v2.8.7.jar
[扫地娘]NeverLag1.3.0.jar
[报错屏蔽]ConsoleSpamFix-1.4.0-1.7.10-1.12.jar
[方块查询]CoreProtect_2.10.0_CNcb1.79.jar
[方块锁]EntityLWC-2.0.7.jar
[权限管理]EssentialsXGroupManager.jar
[标语]ColorMOTD.jar
[死亡不掉落]DoKeepInventory.jar
[死亡信息]DeathMessages.jar
[点券插件]PlayerPoints.jar
[物品封禁]BanItem_with_NBT_v3.2.38.jar
[登录传送]tpLogin.jar
[登录插件]AuthMe-5.4.0.jar
[等级血量]TRCStudioLevelSystem.jar
[箱子商店]QuickShop-0.9.35.jar
[经济插件]iConomy7.05.jar
[背包查看]OpenInv.jar
[自动公告]AutoMessage.jar
[自动复活]AutoRespawn.jar
[菜单]ChestCommands.jar
[虚空世界]VoidWorld.jar
[计分板]MiaoBoard.jar
[跨服列表]BungeeTabListPlus_BukkitBridge-2.8.10.jar
[跨服聊天]MultiServerChat_Client-经济支持版.jar
[随机传送]BetterRTP.jar
[领地保护]ResAssist4.0.0.jar
[领地插件]Residence4.8.2.0.jar
[高级太阳能修复]BanAdvsunGuiReload.jar
[高级封禁]AdvancedBan-2.1.3-RELEASE.jar
相关mod(全称):
A-Pre-Aroma1997Core-1.12.2-2.0.0.0.jar
A-Pre-BrandonsCore-1.12.2-2.4.9.195-universal.jar
A-Pre-CoFHCore-1.12.2-4.5.3.20-universal.jar
A-Pre-CoFHWorld-1.12.2-1.2.0.5-universal.jar
A-Pre-CreativeCore_v1.9.25_mc1.12.2.jar
A-Pre-CTM-MC1.12.2-0.3.3.22.jar
A-Pre-DummyCoreUnofficial-2.4.112.5.jar
A-Pre-EBLib-6.0.2.5.jar
A-Pre-Forgelin-1.8.2.jar
A-Pre-FTBLib-4.2.5.jar
A-Pre-Mantle-1.12-1.3.1.21.jar
A-Pre-MicdoodleCore-1.12.2-4.0.1.181.jar
A-Pre-MJRLegendsLib-1.12.2-1.1.5.jar
A-Pre-p455w0rdslib-1.12.2-2.1.44.jar
A-Pre-RedstoneFlux-1.12-2.0.2.3-universal.jar
A-Pre-Tatw-1.12.2-1.0.1.2.b27.jar
A-Pre-ThermalFoundation-1.12.2-2.5.0.19-universal.jar
B-Bas-AppleCore-mc1.12.2-3.2.0.jar
B-Bas-CraftTweaker2-1.12-4.1.8.jar
B-Bas-CustomNPCs_1.12.2(30Jan19).jar
B-Bas-FTBUtilities-4.2.4.jar
B-Bas-nodestroy-0.1.jar
Baubles-1.12-1.5.2.jar
C-Aux-backpack-3.0.2-1.12.2.jar
C-Aux-BetterRecords-1.12.2-1.6.1.jar
C-Aux-CarryOn-MC1.12.2-v1.12.1.jar
C-Aux-cfm-4.1.5-mc1.12.jar
C-Aux-Chisel-MC1.12.2-0.2.1.35.jar
C-Aux-gravestone-1.10.1.jar
C-Aux-ironchest-1.12.2-7.0.40.824.jar
C-Aux-japaricraftmod-1.12.2-5.4.5.jar
C-Aux-NaturesCompass-1.12.2-1.5.1.jar
CodeChickenLib-1.12.2-3.2.0.345-universal.jar
D-Fix-AnotherCommonBugFix-1.0.1-1.12.2.jar
D-Fix-phosphor-1.12.2-0.2.4+build46-universal.jar
D-Fix-TileEntityLimiter-1.12.2-1.0.2.jar
D-Fix-VanillaFix-1.0.9-97.jar
E-Env-BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar
E-Env-Bloodmoon-MC1.12.2-1.5.3.jar
E-Env-DynamicTrees-1.12.2-0.9.5.jar
E-Env-DynamicTreesBOP-1.12.2-1.4.1e.jar
E-Env-DynamicTreesPHC-1.12.2-1.4.2.jar
E-Env-DynamicTreesTC-1.12.2-1.4.1e.jar
E-Env-GeographiCraft-1.12-0.8.9b.jar
E-Env-ItemPhysic_Full_1.4.13_mc1.12.2.jar
E-Env-natura-1.12.2-4.3.2.62.jar
E-Env-QuickLeafDecay-MC1.12.1-1.2.4.jar
E-Env-RoguelikeDungeons-1.12.2-1.8.0.jar
E-Env-RTG-1.12.2-6.1.0.0-beta.6.jar
E-Env-ToughAsNails-1.12.2-3.1.0.139-universal.jar
F-Tol-conarm-1.12.2-1.2.4.jar
F-Tol-TConstruct-1.12.2-2.10.1.87.jar
F-Tol-TinkerToolLeveling-1.12.2-1.1.0.jar
F-Tol-tooltweaks-1.0.7.jar
G-Frm-CookingForBlockheads_1.12.2-6.4.71.jar
G-Frm-Croparia-2.0_alpha_6.jar
G-Frm-forestry_1.12.2-5.8.0.250.jar
G-Frm-Nutrition-1.12.2-4.3.0.jar
G-Frm-Pam'sHarvestCraft-1.12.2zd Surprise for Yogcast.jar
H-Tec-Advanced-Solar-Panels-4.2.0.jar
H-Tec-appliedenergistics2-rv5-stable-11.jar
H-Tec-Draconic-Evolution-1.12.2-2.3.18.329-universal.jar
H-Tec-ExtraPlanets-1.12.2-0.4.0.jar
H-Tec-Galacticraft-Planets-1.12.2-4.0.1.181.jar
H-Tec-GalacticraftCore-1.12.2-4.0.1.181.jar
H-Tec-GravitationSuite-3.1.0.jar
H-Tec-ImmersiveEngineering-0.12-88.jar
H-Tec-industrialcraft-2-2.8.109-ex112.jar
H-Tec-NuclearCraft-2.10p--1.12.2.jar
H-Tec-ThermalExpansion-1.12.2-5.5.0.29-universal.jar
H-Tec-ToughExpansion-1.12-3.4.24.jar
I-Mgc-Botania-r1.10-354.jar
I-Mgc-ExtraBotany-r1.1-29.jar
I-Mgc-Thaumcraft-1.12.2-6.1.BETA26.jar
I-Mgc-thaumicbases-3.2.270.4r.jar
I-Mgc-thaumictinkerer-1.12.2-5.0-353c71c.jar
J-Slashblade-ExBlades-mc1.12.2-r1.jar
J-SlashBlade-mc1.12-r20.jar
J-SlashBladeTic-V1.0.8-MC1.12.2.jar
J-Terrablade-r1.0-1.jar
[优化]foamfix-0.10.5-1.12.2.jar
[优化]Realtime-1.1.jar
[前置]mixin-0.7.11.jar

报错日志链接(paste.ubuntu.com): 
https://paste.ubuntu.com/p/zR5bmjjTnb/
(如有截图/视频/说明请在下方附链接/说明)
使用猫端pro，服务器启动刚一下就报错。但是换成猫端个人版就完全能启动，求解决

**Comment by Luohuayu** [comment]
请删除D-Fix-phosphor-1.12.2-0.2.4+build46-universal.jar
Pro已经自带优化,会与该MOD的优化冲突

**Comment by zmwwxa** [comment]
> 请删除D-Fix-phosphor-1.12.2-0.2.4+build46-universal.jar
> Pro已经自带优化,会与该MOD的优化冲突

好的，谢谢。。请问有没有pro会与哪些MOD和插件会有优化冲突的列表，以便我们整合的时候直接不采用
