### ISSUE TITLE
暮色森林报错问题

### ISSUE THREAD

**Issue by 1CPOWER** [catserver-3-0/CatServerRepo#12]
请如实填写以下信息 否则不予以处理

服务端版本(/version指令获取):
git-CatServer-1.12.2-78df914

Java版本(打开cmd 输入java -version):
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

操作系统(Linux/Windows, 请指定详细发行版本):
Windows Server 2016

插件列表(/plugins指令):
PlaceholderAPI, OtherAnimalTeleport, PlugMan, DailyReward, GuoItemLoreCommand, NoSellLoreItemToGlobalShop, BossBarAPI, BanItem, EasyWhitelist, TabPrefixFix, AdvancedKitsReloaded, Soulbound, AnimationLib, WorldEdit, OpenInv, MagicBottle, PacketListenerApi, DisableJoinMessage, WorldBorder, MessageAnnouncer, AudioBuffer, LaggRemover, Multiverse-Core, ProtocolLib, HologramGlow, LibsDisguises, CommandBan, KungFu, PermissionsEx, SQLibrary, LangUtils, GlobalShop, Vault, PlayerParticles, Lores, PingFix, Coins, MiaoChat, LiteBoard, NeverLag, HolographicDisplays, TabooLib, QuickShop, Marriage, PlayerPoints, WorldGuard, GrScriptBlock, MythicMobs, ChestCommands, GangsPlus, PrefixManager, BetterRTP, CratesPlus, MythicMobsExtension, Essentials, SX-Attribute, AnimatorStands, GadgetsMenu, ColorMOTD, Jobs, HeadDatabase, RPGshop, BannerMaker, Citizens, Residence, DivineItemsRPG, HolographicExtension, EnchantsPlus, CitizensCMD, LockettePro, MoreFish, EssentialsProtect, ServerSigns, EssentialsSpawn, TitleManager, AuthMe, LiteBans

相关mod(全称):
暮色森林 twilightforest-1.12.2-3.8.689-universal

报错日志链接(paste.ubuntu.com): 
https://paste.ubuntu.com/p/kbjycPXj3M/

(如有截图/视频/说明请在下方附链接/说明)

服务器时不时就刷这个报错..

**Comment by Luohuayu** [comment]
请反馈暮色森林作者
