### ISSUE TITLE
crash java.lang.ArrayIndexOutOfBoundsException: -2105775969

### ISSUE THREAD

**Issue by Coloryr** [catserver-3-0/CatServerRepo#14]
服务端版本:This server is running CatServer version git-CatServer-1.12.2-59b6005 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2838) 
我用的是cat-pro
Java版本:jdk-8.0.222.10-hotspot
操作系统:Windows Server 2019
插件列表:Plugins (17): LuckPerms, WorldEdit, PlaceholderAPI, PetBlocks, spark, Vault, BungeeTabListPlus, Multiverse-Core, ProtocolLib, SuperLobby, ChestCommands, MiaoChat, Essentials, EssentialsChat, PrefixManager, HolographicDisplays, EssentialsSpawn 
相关mod:未知
报错日志链接: https://paste.ubuntu.com/p/BBgrbf88FP/

**Comment by Luohuayu** [comment]
请尝试排除coremod
