### ISSUE TITLE
高级火箭相关

### ISSUE THREAD

**Issue by alex450** [catserver-3-0/CatServerRepo#18]
服务端版本(/version指令获取):
CatServer version git-CatServer-1.12.2-e88142a （pro）
Java版本(打开cmd 输入java -version):
oracle jre8u191 x64
操作系统(Linux/Windows, 请指定详细发行版本):
centos7 5.2.8-1.el7.elrepo.x86_64 
插件列表(/plugins指令):
YouAreNotLostConnection, AsyncWorldEditInjector, LuckPerms, Itemizer, CatResidenceAssist, Stp, PlaceholderAPI, ClearLag, AutoMessage, CustomPrefixes, spark, WorldBorder, Horizon, AntiEMP, CrowdLocator, ProtocolLib, AsyncWorldEdit, VoidGenerator, WorldEditCrashFix, KeepInvandEXP, BanItem, SX-Level, SQLibrary, LangUtils, ChunkLoaderRE, Vault, CatIC2LaserBridge, WorldEdit, LWC, HolographicDisplays, PlotSquared, QuickShop, PlayerPoints, WorldGuard, Multiverse-Core, VipSystem, FreeBungeeChat, TradeMe, ChestCommands, BossShop, BetterRTP, BungeeTabListPlus, MysqlPlayerDataBridge, SX-Attribute, TouchscreenHolograms, CMI   

相关mod(全称):
高级火箭 AdvancedRocketry
报错日志链接(paste.ubuntu.com): 
https://paste.ubuntu.com/p/RGW6DhCcmn/
(如有截图/视频/说明请在下方附链接/说明)
比较神奇的一点是每次爆炸以后删掉空间站世界的 level.dat以后可以继续开

**Comment by KomiMoe** [comment]
请反馈给mod作者。
