### ISSUE TITLE
mod中自定义药水变成不可获得的药水

### ISSUE THREAD

**Issue by JJLeo** [catserver-3-0/CatServerRepo#2]
请如实填写以下信息 否则不予以处理

服务端版本(/version指令获取):
git-CatServer-1.12.2-a1adbd7
Java版本(打开cmd 输入java -version):
1.8.0_144
操作系统(Linux/Windows, 请指定详细发行版本):
Windows 10
插件列表(/plugins指令):
无
报错日志链接(paste.ubuntu.com): 
无
(如有截图/视频/说明请在下方附链接/说明)
将mod中自定义的药水从创造模式物品栏中获取，或者通过酿造获得后，会直接变成“不可获得的药水”，导致原药水无法使用。

**Comment by Luohuayu** [comment]
具体mod?

**Comment by JJLeo** [comment]
> 具体mod?
ToughAsNails-1.12.2-3.1.0.139-universal

**Comment by JJLeo** [comment]
> 具体mod?

我自己写了一个mod自定义了一个药水，也是一样的bug，所有mod里面加的自定义药水都不可用，和mod无关

**Comment by Luohuayu** [comment]
已修复
