### ISSUE TITLE
RTG真实地形+气候控制+超多生物群系无法启动

### ISSUE THREAD

**Issue by skyliye** [catserver-3-0/CatServerRepo#20]
请如实填写以下信息 否则不予以处理

服务端版本(/version指令获取):git-CatServer-1.12.2-e88142a（pro）

Java版本(打开cmd 输入java -version):64位J8 221

操作系统(Linux/Windows, 请指定详细发行版本):Windows server 2012 R2

插件列表(/plugins指令):已确认崩服与插件无关

相关mod(全称):
这三个是导致崩服的mod，既使只添加这三个也会崩溃
GeographiCraft-1.12-0.8.9b
BiomesOPlenty-1.12.2-7.0.1.2439
RTG-1.12.2-6.1.0.0-beta.10

报错日志链接(paste.ubuntu.com):
崩溃报告：https://paste.ubuntu.com/p/fn4TCvZx4r/
latest.log：https://paste.ubuntu.com/p/FgXyNw9Xp5/

**Comment by skyliye** [comment]
补充，使用个人版核心可正常启动，换成pro无法启动

**Comment by Luohuayu** [comment]
已修复 请更新

**Comment by KomiMoe** [comment]
服务端都不是最新版你说个锤子
