### ISSUE TITLE
玩家死亡后back会导致击杀的怪物消失

### ISSUE THREAD

**Issue by heiseshuishan** [catserver-3-0/CatServerRepo#22]
服务端版本(/version指令获取):
git-CatServer-1.12.2-0e503a0

Java版本(打开cmd 输入java -version):
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

操作系统(Linux/Windows, 请指定详细发行版本):
CentOS-6.8 64

插件列表(/plugins指令):
Plugins (12): ClearLag, StopBoom, NoSpawnChunks, Vault, GroupManager, ProtocolLib, deathdrop, Essentials, EssentialsProtect, EssentialsSpawn, EssentialsChat, AuthMe

相关mod(全称):
已经测试没有mod也会出现该问题

详细问题:
经过测试以上插件在Spigot上并不会导致怪物消失的问题，在CatServer上同样的插件没有MOD，会导致怪物击杀玩家后，玩家使用/back 会出现刚刚击杀玩家的怪物被清理！

**Comment by Luohuayu** [comment]
forge相关优化 不属于bug
