### ISSUE TITLE
最新版量子RPG报错

### ISSUE THREAD

**Issue by nanchen11** [catserver-3-0/CatServerRepo#24]
请如实填写以下信息 否则不予以处理

服务端版本(/version指令获取):
[19:59:35] [Server thread/INFO]: This server is running CatServer version git-1.12.2-9f7b76c8 (MC: 1.12.2) (Implementing API versi
on 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2838)

Java版本(打开cmd 输入java -version):
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
PS C:\Users\Administrator>

操作系统(Linux/Windows, 请指定详细发行版本):
Windows Server 2012 R2 Standard
2013 Microsoft Corporation

插件列表(/plugins指令):
[20:05:31] [Server thread/INFO]: Plugins (77): ItemDurability, ZombieNoBurn, PlaceholderAPI, GroupManager, MythicLib, PlugMan, ASK
iller, SkillAPIHook, DailyReward, WorldCommandBlock, GuoItemLoreCommand, BanItem, WuXia, CNPCE, FancyCropTrample, MXBukkitLib, Dru
gs, WorldEdit, Forge, Watcher, TabletAPI, AgarthaLib, CrackShot, WorldBorder, KiteBoard, LaggRemover, ProtocolLib, NoRename, MCCor
e, levelgift, AutoRespawnPlus, LeveledItem, LevelChat, Vexhorn, Mcrmb, Vault, VexRecharge, Lores, ClawVIP, CrazyCrates, GPS, Never
Lag, PlotSquared, HolographicDisplays, PlayerPoints, WorldGuard, MyItems, CustomGo, SkillAPI, EasyKitsRel, ChestCommands, RPGInven
tory, Companions, Essentials, ColorMOTD, NoPluginStealers, BountyHunters, Multiverse-Core, TreasureChest, Residence, EssentialsCha
t, RenameCard-Rel, AncientGates, ScriptBlockPlus, BlockParticles, FPSHelper, PhatLoots, EssentialsSpawn, TradeMe, AuthMe, MythicMo
bs, QuantumRPG, VexView, VexAutoMessage, iTeam, VexKeyBoardHelper, VexRPG-Shop

相关mod(全称):
【各种物品】VariedCommodities_1.12.2(29oct17)
Armourers-Workshop-1.12.2-0.49.1
CustomMC-1.12.2
lycanitesmobs
nashorn
动物单车AnimalBikes_1.12.2(13Jan19)
小动物betteranimalsplus-5.0.1
自定义机器人CustomNPCs_1.12.2(30Jan19)(3)

报错日志链接(paste.ubuntu.com): 

https://paste.ubuntu.com/p/Qnsyy5CJxd/  最新版的量子RPG报错

**Comment by Luohuayu** [comment]
请看规定 否则拉黑
