### ISSUE TITLE
ItemEditor报错

### ISSUE THREAD

**Issue by LuShanion** [catserver-3-0/CatServerRepo#3]
服务端版本:
git-CatServer-1.12.2-a1adbd7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2838) 

Java版本：
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

操作系统(Linux/Windows, 请指定详细发行版本):
Windows Server 2019 Standard 版本 1809 OS内部版本17763.107

插件列表(/plugins指令):
 LogRP, AntiExplosion, JoinCommands, PlaceholderAPI, GroupManager, WorldMobLimiter, DeathCrystal, InvBack, GuoItemLoreCommand, RandomPlacer, Yum, BanItem, Chenghao, BossShop, VexView, CoreProtect, ItemEditor, MultiRobot, WorldEdit, ColorChat, Skript, FastRespawn, MoreCrafting, spark, ProtocolLib, HologramPlus, ArvinLib, MOTDColor, Vault, CrazyCrates, TabooMenu, NeverLag, LWC, PlotSquared, WorldGuard, Guilds, Essentials, PvPTitles, TimedFly, ColorMOTD, SaneEconomy, Multiverse-Core, Residence, EssentialsChat, QuickShop, EssentialsProtect, EssentialsSpawn, ExtraPlugin 

相关mod(全称):
无
报错日志链接(paste.ubuntu.com): 
相关插件名称：ItemEditor
https://paste.ubuntu.com/p/GzxZ8Y9TZj/
(如有截图/视频/说明请在下方附链接/说明)
咨询了几个其他用户，他们使用spigot1.12.2版本核心未发现该问题，同时已经将报错内容发送给了核心作者。
插件论坛帖：
https://www.mcbbs.net/forum.php?mod=viewthread&tid=701766
插件文档:
https://chenji.gitbooks.io/itemeditor-wiki/content/

**Comment by Luohuayu** [comment]
插件使用ASM修改服务端 无法兼容

**Comment by LuShanion** [comment]
谢谢
