### ISSUE TITLE
自己写了个插件 Spigot上运行良好 CatPro上不行

### ISSUE THREAD

**Issue by alex450** [catserver-3-0/CatServerRepo#6]
请如实填写以下信息 否则不予以处理

服务端版本(/version指令获取):
git-CatServer-1.12.2-f278da8 (pro版)

Java版本(打开cmd 输入java -version):
openjdk version "1.8.0_222" 
OpenJDK Runtime Environment (build 1.8.0_222-b10) 
 OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode) 

操作系统(Linux/Windows, 请指定详细发行版本):
Centos7
插件列表(/plugins指令):
Plugins (43): YouAreNotLostConnection, AsyncWorldEditInjector, LuckPerms, CatResidenceAssist, Itemizer, PlaceholderAPI, ClearLag, AutoMessage, spark, WorldBorder, AntiEMP, CrowdLocator, ProtocolLib, AsyncWorldEdit, WorldEditCrashFix, KeepInvandEXP, BanItem, SQLibrary, SX-Level, LangUtils, VexRMB, SuperMOTD, Vault, ChunkLoaderRE, CatIC2LaserBridge, WorldEdit, LWC, HolographicDisplays, PlotSquared, QuickShop, PlayerPoints, Multiverse-Core, WorldGuard, VipSystem, ChestCommands, BossShop, BetterRTP, SX-Attribute, AuthMe, TouchscreenHolograms, CMI, Residence, TradeMe

相关mod(全称):
我相信这个问题和mod无关，因为我试了一下catpro不装任何mod都这样

报错日志链接(paste.ubuntu.com): 
报错：https://paste.ubuntu.com/p/GWjnG4488G/
插件源码（就一个主类）：https://paste.ubuntu.com/p/9XCY643Pd7/
(如有截图/视频/说明请在下方附链接/说明)

我测试了catpro环境和spigot环境，插件一样，在spigot上工作，pro上不工作
spigot 版本 git-Spigot-f982156-22564a9 

![N9942E@138N}FEREB$4P@(K](https://user-images.githubusercontent.com/17879601/62923349-1c803900-bde0-11e9-8905-73dd405190ba.png)

**Comment by alex450** [comment]
插件效果和图里一样是个actionbar显血的，至于为什么一片黑是我测试的时候把自己埋地下了

**Comment by Luohuayu** [comment]
尝试关闭ProtocolLib的background compiler选项或者与ProtocolLib作者反馈

**Comment by KomiMoe** [comment]
https://github.com/dmulloy2/ProtocolLib/pull/551
啊。被怼的好惨啊，说我太暴力了

**Comment by alex450** [comment]
> [dmulloy2/ProtocolLib#551](https://github.com/dmulloy2/ProtocolLib/pull/551)
> 啊。被怼的好惨啊，说我太暴力了

我试了一下关闭background complier无效

**Comment by Luohuayu** [comment]
> 
> 
> > [dmulloy2/ProtocolLib#551](https://github.com/dmulloy2/ProtocolLib/pull/551)
> > 啊。被怼的好惨啊，说我太暴力了
> 
> 我试了一下关闭background complier无效

请与ProtocolLib作者反馈
