### ISSUE TITLE
BKCommonLib 不兼容

### ISSUE THREAD

**Issue by he714023166** [catserver-3-0/CatServerRepo#7]
请如实填写以下信息 否则不予以处理

服务端版本(/version指令获取):
git-CatServer-1.12.2-c719bd5 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2838) 
Java版本(打开cmd 输入java -version):
1.8.0_221
操作系统(Linux/Windows, 请指定详细发行版本):
Windows
插件列表(/plugins指令):
Plugins (122): §aChatReplace§f, §aItemDurability§f, §aSX-Command§f, §aMythicLib§f, §aJdbcConnectionBridge§f, §aNoFishRepair§f, §aConsoleCommands§f, §aConsoleSpamFix§f, §aDeluxeTags§f, §aNoSellLoreItemToGlobalShop§f, §aRandomPlacer§f, §aBackWordLeave§f, §aPlayerLevels§f, §aAT§f, §aPointShop§f, §aDrugs§f, §aEggCatcher�靎, §aTimeLikeMe§f, §aAudioBuffer§f, §aLaggRemover§f, §aProtocolLib§f, §aEntityStack§f, §aNothingToBreak§f, §aDeathMessagesPrime§f, §aMCCore§f, §aLimitedheight§f, §aSweepAttack§f, §aVoidGenerator§f, §aBreakDown§f, §aAntiAttack§f, §aPTweaks§f, §aLoreLimit§f, §aResidenceAssist§f, §aAntiBack§f, §aLores§f, §aChunkBlocksLimit§f, §aGroupManager§f, §aWorldMobLimiter§f, §aBoss§f, §aItemUseLimit§f, §atpLogin§f, §aBetonQuest§f, §aDantiao§f, §aGuoItemLoreCommand§f, §aCustomDrops§f, §aCustomBaoShi§f, §aBanItem§f, §aSoulbound§f, §aWorldEdit§f, §aPlayerCommands§f, §aTrash§f, §aIllegalStack§f, §aWorldBorder§f, §aRandomizedLore§f, §aCheckLores§f, §aSoulBound-expand§f, §aNOMoreDamageEffect§f, §aPlayerJoinMessage§f, §aSQLibrary§f, §aEffectLib§f, §aGlobalShop§f, §aVault§f, §cBKCommonLib§f, §aNeverLag§f, §aLWC§f, §aHolographicDisplays§f, §aMysteriousStrengthen§f, §aPlayerPoints§f, §aLocyCommand§f, §aShopGUIPlus§f, §aTitleDomain§f, §aSkript§f, §aScriptMobs§f, §aRPGshop§f, §aCitizens§f, §aGemsEconomy§f, §aPlaceholderAPI§f, §aPlotSquared§f, §aCustomGo§f, §aSkillAPI§f, §aDomainAudio§f, §aRevive§f, §aEssentials§f, §cLightCleaner§f, §aResidence§f, §aAdvancedAchievements§f, §aGlobalPrefix§f, §aResidenceFixer§f, §aVipSystem§f, §aGrScriptBlock§f, §aGuoGroupCommand§f, §aEpicCraftingsPlus§f, §aCustomGo-Tili§f, §aTitleManager§f, §aMCSign§f, §aKeyboardMaster§f, §aRealSurvival§f, §aMultiverse-Core§f, §aTradeMe§f, §aTabooMenu§f, §aMiaoChat§f, §aVipStorage§f, §aEssentialsProtect§f, §aEssentialsAntiBuild§f, §aEssentialsSpawn§f, §aAuthMe§f, §aPhatLoots§f, §aCropPlus§f, §aServerTutorialPlus§f, §aVexView§f, §aVexHuds§f, §aVexAutoMessage§f, §aVexMaster§f, §aMythicMobs§f, §aVanillaInventoryKiller§f, §aSX-Attribute§f, §aVexRPG-Shop§f, §aVexInteractSystem§f, §aMythicMobsExtension§f, §aMythicMobItemHandler§f, §aSharpSK§f, §aMythicArtifacts
相关mod(全称):
BKCommonLib
报错日志链接(paste.ubuntu.com): 
https://paste.ubuntu.com/p/h8cNj78F4g/
(如有截图/视频/说明请在下方附链接/说明)

**Comment by Luohuayu** [comment]
该插件使用奇葩反射方法 无法兼容
