### ISSUE TITLE
BKCommonLib不能初始化

### ISSUE THREAD

**Issue by SkYoyo** [catserver-3-0/CatServerRepo#8]
请如实填写以下信息 否则不予以处理

服务端版本(/version指令获取):
This server is running CatServer version git-CatServer-1.12.2-c719bd5 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2838)
Java版本(打开cmd 输入java -version):
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
操作系统(Linux/Windows, 请指定详细发行版本):
Windows 7 SP1 X64
插件列表(/plugins指令):
Plugins (1): BKCommonLib
相关mod(全称):
无
报错日志链接(paste.ubuntu.com): 
https://yun.mc5173.com/images/2019/08/14/1.png
https://yun.mc5173.com/images/2019/08/14/2.png
(如有截图/视频/说明请在下方附链接/说明)

**Comment by Luohuayu** [comment]
请勿截图报错
