### ISSUE TITLE
appliedenergistics2 无法进入空间元件内部空间，传送坐标错误

### ISSUE THREAD

**Issue by YonChun** [catserver-3-0/CatServerRepo#9]
请如实填写以下信息 否则不予以处理

服务端版本(/version指令获取): 
    CatServer version git-CatServer-1.12.2-ab8e8dc (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2838)
Java版本(打开cmd 输入java -version):
    java 1.8.0_201
操作系统(Linux/Windows, 请指定详细发行版本):
    windows 10 1803
插件列表(/plugins指令):
    PluginConstructorAPI, WorldEdit, ProtocolLib
相关mod(全称):
    appliedenergistics2-rv6-stable-7.jar
报错日志链接(paste.ubuntu.com): 
    无
(如有截图/视频/说明请在下方附链接/说明)

空间塔能正常存储和释放方块，但是不能将玩家传送进元件的空间。传送进去的却是 x0 y256 z0 的位置（空无一物）
单人生存和 Sponge服务端能够正常使用，可能CatServer不兼容mod传送其他世界的功能？
![WP2)Z0N3 $(EWBNZ(EBDJ)C](https://user-images.githubusercontent.com/27072445/63081844-40c24e00-bf77-11e9-8a0d-497896cce6a6.png)
![N%NLGC}FJ1ZG{X)BEY0GXLO](https://user-images.githubusercontent.com/27072445/63081846-40c24e00-bf77-11e9-8881-33c6300dc4ff.png)

**Comment by Luohuayu** [comment]
已尝试修复,其他MOD已正常传送,但AE依然无法正常传送
由于AE作者拒绝对任何非Forge端的支持,暂时无法解决,建议禁用空间塔
